In [1]:
#kadai_003

import numpy as np

a = np.array([[0,1], [2,3], [4,5]])
b = np.array([[0,1,2,3], [4,5,6,7]])

matrix_calc = np.dot(a, b)
print(matrix_calc)

matrix_calc.max()

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47